'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';

type Item={id:number;name:string;description:string;price_cents:number;category:string;image:string|null};
type Cart={id:number;name:string;price_cents:number;quantity:number;image:string|null};
const KEY='fz_cart_v3'; const money=(n:number)=>'R'+(n/100).toFixed(2);
export default function Menu(){const [items,setItems]=useState<Item[]|null>(null);const [cart,setCart]=useState<Cart[]>([]);const [cat,setCat]=useState('All');const [search,setSearch]=useState('');
useEffect(()=>{fetch('/api/menu').then(r=>r.json()).then(d=>setItems(d.items||[]));try{setCart(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}},[]);
function add(i:Item){const next=[...cart];const x=next.find(x=>x.id===i.id);if(x)x.quantity++;else next.push({id:i.id,name:i.name,price_cents:i.price_cents,quantity:1,image:i.image});setCart(next);localStorage.setItem(KEY,JSON.stringify(next))}
const cats=useMemo(()=>['All',...Array.from(new Set((items||[]).map(x=>x.category)))],[items]);const shown=(items||[]).filter(x=>(cat==='All'||x.category===cat)&&(!search||x.name.toLowerCase().includes(search.toLowerCase())));
const count=cart.reduce((s,x)=>s+x.quantity,0);
return <main className="menu-page"><header className="top"><Link href="/" className="brand">FOODIE ZONE</Link><div className="links"><Link href="/orders" className="secondary">My Orders</Link><Link href="/dashboard" className="secondary">Rewards</Link><Link href="/cart" className="order">Cart ({count})</Link></div></header><div className="wrap"><section className="hero"><h1>Our Menu</h1><p>Order directly from Foodie Zone. Every completed order earns 25% of its value as points.</p></section><div className="notice"><strong>Order here. Earn rewards automatically.</strong> Your account, orders and Foodie Points all work together.</div><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the menu..."/></div><div className="catbar"><div className="chips">{cats.map(c=><button key={c} className={'chip '+(c===cat?'on':'')} onClick={()=>setCat(c)}>{c}</button>)}</div></div>{!items&&<div className="card">Loading menu...</div>}{items&&<div className="menu-grid">{shown.map(i=><article className="menu-card" key={i.id}>{i.image?<img className="menu-img" src={i.image} alt={i.name}/>:<div className="menu-img menu-ph">{i.name.charAt(0)}</div>}<div className="menu-body"><h3>{i.name}</h3>{i.description&&<p className="menu-desc">{i.description}</p>}<div className="menu-foot"><strong className="menu-price">{money(i.price_cents)}</strong><button className="button button-pink" onClick={()=>add(i)}>Add</button></div></div></article>)}</div>}</div>{count>0&&<div className="order-bar"><Link href="/cart" className="button button-pink button-large">View cart · {count} item{count===1?'':'s'}</Link></div>}</main>}