'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
type Cart={id:number;name:string;price_cents:number;quantity:number};
const KEY='fz_cart_v3'; const money=(n:number)=>'R'+(n/100).toFixed(2);
export default function Checkout(){const router=useRouter();const [cart,setCart]=useState<Cart[]>([]);const [type,setType]=useState('pickup');const [pay,setPay]=useState('cash');const [name,setName]=useState('');const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const [notes,setNotes]=useState('');const [err,setErr]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}},[]);const subtotal=cart.reduce((s,x)=>s+x.price_cents*x.quantity,0),fee=type==='delivery'?2500:0,total=subtotal+fee;
async function place(e:React.FormEvent){e.preventDefault();setErr('');setBusy(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart,orderType:type,paymentMethod:pay,customerName:name,customerPhone:phone,deliveryAddress:address,notes})});const d=await r.json();if(r.status===401){router.push('/login?next=/checkout');return}if(!r.ok){setErr(d.error||'Could not place order');return}localStorage.removeItem(KEY);router.push('/orders?new='+encodeURIComponent(d.orderNumber))}catch{setErr('Unable to place the order right now.')}finally{setBusy(false)}}
if(!cart.length)return <main className="wrap"><div className="card form"><h1>Your cart is empty</h1><Link href="/menu">Go to menu</Link></div></main>;
return <main className="wrap"><div className="hero"><h1>Checkout</h1><p>Your order and rewards stay together in your Foodie Zone account.</p></div><div className="split-order"><form className="card form" style={{margin:0,maxWidth:'none'}} onSubmit={place}>{err&&<div className="error">{err}</div>}<div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Phone</label><input value={phone} onChange={e=>setPhone(e.target.value)} required/></div><div className="field"><label>Order type</label><div className="choice"><label><input type="radio" checked={type==='pickup'} onChange={()=>setType('pickup')}/> Pickup</label><label><input type="radio" checked={type==='delivery'} onChange={()=>setType('delivery')}/> Delivery</label></div></div>{type==='delivery'&&<div className="field"><label>Delivery address</label><textarea value={address} onChange={e=>setAddress(e.target.value)} required rows={4}/></div>}<div className="field"><label>Payment</label><div className="choice"><label><input type="radio" checked={pay==='cash'} onChange={()=>setPay('cash')}/> Cash</label><label><input type="radio" checked={pay==='card'} onChange={()=>setPay('card')}/> Card</label></div></div><div className="field"><label>Order notes (optional)</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></div><button className="primary" disabled={busy}>{busy?'Placing order...':'Place order'}</button></form><aside className="card"><h2>Order summary</h2>{cart.map(x=><div className="tot" key={x.id}><span>{x.quantity} × {x.name}</span><strong>{money(x.price_cents*x.quantity)}</strong></div>)}<div className="tot"><span>Subtotal</span><strong>{money(subtotal)}</strong></div>{fee>0&&<div className="tot"><span>Delivery</span><strong>{money(fee)}</strong></div>}<div className="tot big"><span>Total</span><span>{money(total)}</span></div><p className="muted">Points are calculated at 25% of the completed order total.</p></aside></div></main>}