'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
export default function ResetPassword(){
 const router=useRouter(); const [token,setToken]=useState(''); const [p,setP]=useState(''),[c,setC]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false); useEffect(()=>{setToken(new URLSearchParams(window.location.search).get('token')||'')},[]);
 async function submit(e:FormEvent){e.preventDefault();setErr('');if(!token)return setErr('This reset link is missing or invalid.');if(p!==c)return setErr('Passwords do not match.');setBusy(true);try{const res=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:p})});const d=await res.json();if(!res.ok){setErr(d.error||'Unable to reset password.');return}router.push('/login?reset=success')}catch{setErr('Unable to reset password. Please try again.')}finally{setBusy(false)}}
 return <main className="wrap"><div className="card form"><div className="eyebrow">NEW PASSWORD</div><h1>Create a new password</h1><p className="muted">Choose a new password for your Foodie Zone Rewards account.</p>{err&&<div className="error">{err}</div>}<form onSubmit={submit}><div className="field"><label>New password</label><div className="password-field"><input type={show?'text':'password'} minLength={8} value={p} onChange={e=>setP(e.target.value)} autoComplete="new-password" required/><button type="button" className="show-password" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div><span className="muted" style={{fontSize:12,margin:0}}>At least 8 characters, with a letter and a number. No common or sequential passwords (e.g. 1234567890).</span></div><div className="field"><label>Confirm new password</label><input type={show?'text':'password'} minLength={8} value={c} onChange={e=>setC(e.target.value)} autoComplete="new-password" required/></div><button className="primary" disabled={busy}>{busy?'Updating...':'Update password'}</button></form><div className="links"><Link href="/login">Back to login</Link></div></div></main>
}
